# Generated by Django 4.2.10 on 2025-11-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='UsersAdmin',
        ),
        migrations.AlterModelTable(
            name='usersadmin',
            table='users_admin',
        ),
    ]
