# Generated by Django 4.2.10 on 2025-11-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_admin_usersadmin_alter_usersadmin_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersadmin',
            options={'managed': False},
        ),
    ]
