# Generated by Django 4.2.10 on 2025-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersadmin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAdmin',
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
