# Generated by Django 4.2.10 on 2025-11-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0006_alter_turf_owner'),
        ('bookings', '0004_booking_is_cancelled_alter_booking_booked_at_and_more'),
        ('users', '0006_delete_usersadmin_player_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='player',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='notification',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourite',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourite',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.slot'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='cart',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
