# Generated by Django 4.2.10 on 2025-11-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cart_cartitem_favourite_notification_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
