# Generated by Django 4.2.10 on 2025-11-27 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_player_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
