# Generated by Django 4.2.10 on 2025-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_player_city_player_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
