# Generated by Django 5.2.8 on 2025-11-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_alter_turf_owner'),
        ('users', '0002_player_email_player_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='sport_type',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('multi', 'Multi-sport')], default='multi', max_length=20),
        ),
        migrations.AlterField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(default=9750282028, on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='users.owner'),
            preserve_default=False,
        ),
    ]
