# Generated by Django 5.2.8 on 2025-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_turf_sport_type_alter_turf_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
