# Generated by Django 5.2.8 on 2025-11-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_turf_is_active'),
        ('users', '0002_player_email_player_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turfs', to='users.owner'),
        ),
    ]
