# Generated by Django 4.2.10 on 2025-11-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfs', '0005_alter_turf_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_turfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
