# Generated by Django 5.2.8 on 2025-11-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.turf'),
        ),
    ]
