# Generated by Django 5.2.8 on 2025-11-16 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slot',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='turfs.turf'),
        ),
    ]
